### ISSUE TITLE
插件如何在nonebot中使用?

### ISSUE THREAD

**Issue by xzm1274913976** [17TheWord/nonebot-plugin-warframe#4]
仓主你好,我是第一次使用nonebot.
我在nonebot的插件中配置了gocqhttp和warframe两个插件,gocqhttp工作正常也能接受消息,但是发送wf指令给qq后没有响应,我该如何排查?

[project]
name = "wf"
version = "0.1.0"
description = "wf"
readme = "README.md"
requires-python = ">=3.8, <4.0"

[tool.nonebot]
adapters = [
    {name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11"}

]
plugins = ["nonebot_plugin_warframe","nonebot_plugin_gocqhttp"]
plugin_dirs = []
builtin_plugins = []

####

Using python: /root/.local/bin/wf/.venv/bin/python
04-04 10:45:54 [SUCCESS] nonebot | NoneBot is initializing...
04-04 10:45:54 [INFO] nonebot | Current Env: prod
04-04 10:45:55 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_gocqhttp"
04-04 10:45:55 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_warframe"
04-04 10:45:55 [SUCCESS] nonebot | Running NoneBot...
04-04 10:45:55 [INFO] uvicorn | Started server process [30372]
04-04 10:45:55 [INFO] uvicorn | Waiting for application startup.
04-04 11:18:12 [INFO] nonebot_plugin_gocqhttp | [xxxxxxxxxxx] 收到好友 init 3(xxxxxxxxxxx) 的消息: 星际战甲 突击 (1859092336)
04-04 11:18:12 [SUCCESS] nonebot | OneBot V11 xxxxxxxxxxx| [message.private.friend]: Message 1859092336 from xxxxxxxxxxx'星际战甲 突击'

**Comment by xzm1274913976** [comment]
搞定了 cqhttp的ws反向代理没有填写 - .-!

**Comment by 17TheWord** [comment]
我超 这插件都有人用？！
